### PR TITLE
fix the @ts-expect-error

### LINKED ISSUE #1: Fix typing
https://github.com/laranatech/colorana/blob/c17c71e8ceb4f03ad71c194c00206df8dd673e40/src/command-handlers.ts#L39-L40

### PR DESCRIPTION
**Pull request by Abhishekkar123**
#1 fix the issue

### CODE REVIEW

**Comment by e-kucheriavyi** [comment]
Are you sure the isn't a way to solve this issue without `any`?

**Comment by Abhishekkar123** [comment]
Thanks for pointing that out! I’ve corrected it and removed the use of any by properly defining the types to ensure type safety. This way, we maintain the benefits of TypeScript's type checking

**Comment by e-kucheriavyi** [comment]
I checked it and it compiles and works as it should, but the vscode gives me an error:

```
Type 'string | number | boolean | { (x: number, y: number, w: number, h: number, radii?: number | DOMPointInit | (number | DOMPointInit)[] | undefined): void; (x: number, y: number, w: number, h: number, radii?: number | ... 2 more ... | undefined): void; } | ... 46 more ... | { ...; }' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
  ```
  
  Could you fix this, please?

**Comment by Abhishekkar123** [comment]
updated.

File: src/command-handlers.ts [hunk 1]
```diff
@@ -36,8 +36,14 @@ export const commandHandlers: Record<PrimitiveCommandType, CommandHandler> = {
 			if (!(key in ctx)) {
 				return
 			}
-			// @ts-expect-error `Type 'string | number' is not assignable to type 'never'.`
-			ctx[key] = value
+			if (key in ctx) {
```
Comment (e-kucheriavyi) [inline src/command-handlers.ts]: This is unnecessary, because we already have this check in line 36

File: src/command-handlers.ts [hunk 2]
```diff
@@ -36,8 +36,14 @@ export const commandHandlers: Record<PrimitiveCommandType, CommandHandler> = {
...
+				const current = ctx[key as keyof CanvasRenderingContext2D];
+				// console.log("Curr",current)
+				if (typeof current === typeof value) {
+					(ctx as Record<typeof key, typeof value>)[key] = value;
+				//   console.log(key, "-- set to ", value);
```
Comment (e-kucheriavyi) [inline src/command-handlers.ts]: Please, remove comments and semicolons — they are against styleguild

**Review by e-kucheriavyi — COMMENTED** [review]
I finally had time to review it. Great! Please, apply a couple of fixes and we will be ready to merge your MR

File: src/command-handlers.ts (hunk 2 above)
Comment (Abhishekkar123) [reply src/command-handlers.ts]: removed the comment and semicolon in the code . please let me know if anything else needed
